### ISSUE TITLE
Proxy release files through worker

### ISSUE THREAD

**Issue by RyKilleen** [KilleenCode/tauri-update-cloudflare#8]
## Intent

Enable private Github repos to provide Tauri's updater with the necessary update files. Right now a Github-authenticated worker can get the necessary release information, but the Tauri client can't access the files. 

Security is outside the scope of this issue and depends on updates with Tauri: https://github.com/tauri-apps/tauri/issues/3896

## Questions / Considerations

- [x] Limitations with workers? Bandwidth, CPU etc.
As far as I can tell, there aren't any [Cloudflare limits](https://developers.cloudflare.com/workers/platform/limits/) that affect this use case. 

## Implementation

- [ ] Create a route, `/latest/$filename`. This route gets the latest release from the repo, filters assets by file name, requests the file, and feeds the request as the response.
- [ ] Change the response to Tauri's updater request from the github file url to the proxied route. We can base this off of a defined GITHUB_SECRET for now, or add an additional flag.

**Comment by RyKilleen** [comment]
Hey @ghostdevv I see Tauri added the requested feature! Does that mean this issue is no longer needed?

**Comment by ghostdevv** [comment]
Probably not, however it might be good for people who don't wanna ship their gh token in their tauri app

**Comment by RyKilleen** [comment]
I'm going to close this for now, but open to a new request or PRs!

**Comment by ACPixel** [comment]
Not to open up an old issue, but if any work is still being done on this I would also love to have a proxy server in here. I'd love to do it myself but cloudflare workers are not my forte. Would be super nice to have this though!

**Comment by RyKilleen** [comment]
@ACPixel no worries, happy to take a look into it. Does the above describe your needs? is there anything not captured here that should be?

**Comment by ACPixel** [comment]
I think that the issue contains everything that would need to be there. Basically just a route to proxy the files, and would need to make sure the json responses contain links to the proxy instead of the release files directly.

**Comment by RyKilleen** [comment]
@ACPixel @ghostdevv This is now merged and available! Proxying is enabled if a GITHUB token is set, please let me know how it works out for you!

**Comment by ACPixel** [comment]
Amazing! I'll try it out as soon as possible! Thanks again for taking and look and a huge thanks for doing that so quickly!

**Comment by ACPixel** [comment]
Alright got a chance to try it out, everything works as intended except one thing. The actual downloads don't work for private repos as it's trying to proxy the "browser_download_url" which only works via a valid github auth. Adding the auth headers and switching the url from the `browser_download_url` to the `url` on the release json fixes this issue as it then uses the release assets API to get the file.

I'm doing it like this since in my case I only need to handle the private github repo:
```ts
const getLatestAssets = async (request: Request) => {
  const fileName = request.url.split("/")?.at(-1);
  if (!fileName) {
    throw new Error("Could not get file name from download URL");
  }

  const release = await getLatestRelease(request);
  const downloadPath = release.assets.find(
    ({ name }) => name === fileName,
  )?.url;

  if (!downloadPath) {
    throw new Error("Could not get file path from download URL");
  }

  const { readable, writable } = new TransformStream();
  const headers = new Headers({
    Accept: "application/octet-stream",
    "User-Agent": request.headers.get("User-Agent") as string,
  });

  if (GITHUB_TOKEN?.length)
    headers.set("Authorization", `token ${GITHUB_TOKEN}`);
  const file_response = await fetch(downloadPath, {
    method: "GET",
    redirect: "follow",
    headers,
  });

  file_response?.body?.pipeTo(writable);
  return new Response(readable, file_response);
};
```

**Comment by RyKilleen** [comment]
Ah that makes total sense, probably should have set up a private repo to test it fully 😃

Would you mind doing a PR with those changes? Glad you got it working!

**Comment by ACPixel** [comment]
Yeah can do. I have to clean up a couple things I put in while testing but I'll try to get one out tonight. Also had to update typescript version to get the .at() functions you used working.

**Comment by RyKilleen** [comment]
@ACPixel I appreciate that, was attempting to do it pretty hastily and the repo definitely could use a little new years cleaning!

**Comment by ACPixel** [comment]
No problem! Sorry for the delay been a busy week, I'll try to get it cleaned up and ready within the next couple of days haha

**Comment by ghostdevv** [comment]
Awesome! Managed to get this working today with some tweaks to the code

@ACPixel Did you manage to get some time to look at a PR? Lmk if you need any help
